### ISSUE TITLE
Messung Manuell auslösen

### ISSUE THREAD

**Issue by RasputinBerry** [jp112sdl/HB-UNI-Sen-WEIGHT#1]
Hallo jp112sdl,

Du hast mir bereits hier `https://github.com/jp112sdl/HB-UNI-Sen-DIST-TOF/issues/1` geholfen ... Nochmal vielen Dank.
Jetzt wiederhole ich die Bitte für diesen Wägesensor.

_(Ich habe probiert, die Änderungen aus dem Abstandssensor zu verstehen und zu übertragen, bin aber kläglich gescheitert.)_

**Comment by jp112sdl** [comment]
Ich hab das jetzt nochmal gemacht
https://github.com/jp112sdl/HB-UNI-Sen-WEIGHT/tree/dev_manual_measure

1:1 wie im DIST-TOF

**Comment by RasputinBerry** [comment]
Vielen, vielen Dank ... wenn man es kann ist es einfach  ... ;-)
